Function Get-Rhyme() {
    <#
    .SYNOPSIS
    Recite the nursery rhyme 'This is the House that Jack Built'.

    .DESCRIPTION
    Given the start verse and the end verse, return a string reciting the rhyme from that range.

    .PARAMETER Start
    The start verse.

    .PARAMETER End
    The end verse.

    .EXAMPLE
    Get-Rhyme -Start 1 -End 2
    Return:
    @"
    This is the house that Jack built.
    This is the malt that lay in the house that Jack built.
    "@
     #>
    [CmdletBinding()]
    Param(
        [int]$Start,
        [int]$End
    )
    
    $SubjectActions = [Ordered]@{
        "house" = "Jack built"
        "malt" = "lay in"
        "rat" = "ate"
        "cat" = "killed"
        "dog" = "worried"
        "cow with the crumpled horn" = "tossed"
        "maiden all forlorn" ="milked"
        "man all tattered and torn" = "kissed"
        "priest all shaven and shorn" = "married"
        "rooster that crowed in the morn" = "woke"
        "farmer sowing his corn" = "kept"
        "horse and the hound and the horn" = "belonged to"
        # New rhymes lol
        "fox quick and slick" = "stole"
        "duck with a quack" = "swam"
        "goat on a boat" = "floated"
        "bee buzzing in glee" = "hummed around"
        "owl in the night" = "hooted at"
        "mouse so small" = "scurried through"
        "frog on a log" = "leaped over"
        "fish in the stream" = "swam by"
        "bird with a song" = "sang to"
        "pig in the mud" = "wallowed near"
        "sheep with wool" = "grazed beside"
        "ant on a hill" = "carried away"
        "butterfly in the sky" = "fluttered above"
        "spider on the wall" = "crawled up"
        "squirrel in a tree" = "dashed down"
        "snail on the leaf" = "slid over"
        "hare in the field" = "bounded past"
        "deer in the forest" = "trotted through"
        "duckling in the pond" = "paddled around"
        "badger in the den" = "snoozed inside"
        "raven in the air" = "soared above"
        "hedgehog in the hedge" = "curled up"
        "lizard on a rock" = "based on"
        "beetle under the stone" = "crawled beneath"
        "kitten in the basket" = "napped in"
        "puppy in the yard" = "dug up"
        "lamb in the meadow" = "frolicked in"
        "eagle in the mountains" = "perched atop"
        "crab on the shore" = "scuttled along"
        "otter in the river" = "splashed through"
        "moose in the woods" = "ambled in"
        "swan on the lake" = "glided over"
        "peacock in the garden" = "strutted around"
        "parrot in the jungle" = "chattered in"
        "dolphin in the ocean" = "leaped out"
        "tiger in the jungle" = "prowled through"
        "camel in the desert" = "trudged across"
        "penguin in the snow" = "waddled over"
        "monkey in the trees" = "swung through"
        "elephant in the savanna" = "trumpeted in"
        "giraffe with a long neck" = "munched leaves"
        "hippo in the water" = "splashed around"
        "zebra on the plains" = "galloped across"
        "kangaroo in the outback" = "hopped around"
        "koala in the eucalyptus" = "climbed up"
        "rhino charging ahead" = "stomped over"
        "panda in the bamboo" = "munched on"
        "wolf in the forest" = "howled at"
        "lynx in the snow" = "prowled silently"
        "octopus in the sea" = "drifted through"
        "shark in the deep" = "swam swiftly"
        "whale in the ocean" = "breached high"
        "jellyfish under the waves" = "floated gently"
        "starfish on the seabed" = "crawled slowly"
        "clownfish among corals" = "darted about"
        "seahorse in the kelp" = "bobbed along"
        "pelican on the pier" = "dived down"
        "seagull in the sky" = "swooped over"
        "flamingo by the lake" = "stood on one leg"
        "vulture in the desert" = "circled above"
        "albatross over the ocean" = "glided far"
        "hummingbird by the flower" = "hovered near"
        "woodpecker in the forest" = "tapped on"
        "magpie in the garden" = "collected shiny things"
        "cuckoo in the clock" = "called out"
        "salamander under a rock" = "hid away"
        "newt in the pond" = "slinked through"
        "ferret in the burrow" = "dug down"
        "weasel in the brush" = "darted through"
        "ermine in the snow" = "camouflaged well"
        "mole under the earth" = "tunnelled through"
        "bat in the cave" = "flew out at dusk"
        "raccoon by the trashcan" = "rummaged through"
        "porcupine in the woods" = "bristled up"
        "skunk along the path" = "sprayed near"
        "armadillo in the scrub" = "rolled up"
        "sloth in the canopy" = "moved slowly"
        "anteater in the termite mound" = "sniffed around"
        "tapir in the jungle" = "foraged for food"
        "lemur in the treetops" = "leaped between"
        "meerkat on the lookout" = "stood guard"
        "warthog in the savanna" = "rooted around"
        "hyena laughing away" = "cackled at"
        "ibex on the mountain" = "climbed up high"
        "buffalo in the grasslands" = "grazed along"
        "gazelle on the run" = "leapt gracefully"
        "okapi in the underbrush" = "hid away"
        "narwhal in the Arctic" = "dove deep"
        "wombat in the burrow" = "snoozed snugly"
        "platypus in the creek" = "fished curiously"
        "cassowary in the rainforest" = "strutted boldly"
        "quokka on the island" = "smiled widely"
        "wallaby in the bush" = "bounced briskly"
        "echidna on the trail" = "shuffled along"
        "dugong in the bay" = "grazed peacefully"
        "cockatoo in the tree" = "screeched loudly"
        "kookaburra by the river" = "laughed merrily"
        "numbat in the log" = "foraged intently"
        "bilby under the moon" = "dug busily"
        "emperor penguin in the snow" = "huddled together"
        "kiwi in the thicket" = "poked around"
        "toucan in the canopy" = "flapped colourfully"
        "lemming in the tundra" = "scampered about"
        "snow leopard in the mountains" = "stalked silently"
        "orangutan in the forest" = "swung gracefully"
        "gibbon in the trees" = "sang loudly"
        "bonobo by the stream" = "played joyfully"
        "mandrill in the jungle" = "groomed carefully"
        "marmoset in the branches" = "leapt nimbly"
        "proboscis monkey by the river" = "snoozed lazily"
        "aye-aye in the night" = "tapped stealthily"
        "sifaka in the foliage" = "danced elegantly"
        "capuchin in the grove" = "foraged smartly"
        "macaque in the hills" = "scampered playfully"
        "chimpanzee in the savanna" = "climbed skilfully"
        "gorilla in the mist" = "beat its chest"
        "red panda in the tree" = "nibbled sleepily"
        "sloth bear in the cave" = "shuffled clumsily"
        "sun bear in the forest" = "climbed expertly"
        "polar bear on the ice" = "prowled hungrily"
        "grizzly bear by the river" = "fished adeptly"
        "black bear in the woods" = "foraged hungrily"
        "spectacled bear in the Andes" = "climbed deftly"
        "panda bear in the grove" = "munched contentedly"
        "Asian elephant in the grassland" = "trumpeted grandly"
        "African elephant in the savanna" = "waved its trunk"
        "pygmy elephant by the stream" = "bathed playfully"
        "jaguar in the rainforest" = "prowled stealthily"
        "leopard in the tree" = "lounged lazily"
        "cheetah on the plains" = "sprinted swiftly"
        "snow leopard in the heights" = "leapt gracefully"
        "cougar in the mountains" = "stalked quietly"
        "ocelot in the undergrowth" = "slunk silently"
        "caracal in the desert" = "pounced quickly"
        "serval in the grass" = "leaped high"
        "bobcat in the forest" = "ambushed skilfully"
        "clouded leopard in the canopy" = "climbed nimbly"
        "fossa in the jungle" = "hunted adeptly"
        "margay in the branches" = "climbed gracefully"
        "maned wolf in the pampas" = "trotted elegantly"
        "Ethiopian wolf in the highlands" = "prowled alertly"
        "arctic fox in the snow" = "camouflaged cleverly"
        "fennec fox in the desert" = "dug swiftly"
        "red fox in the meadow" = "scurried sneakily"
        "Gray fox in the woods" = "climbed trees"
        "bat-eared fox in the savanna" = "listened intently"
        "Bengal tiger in the jungle" = "stalked powerfully"
        "Siberian tiger in the taiga" = "stalked through snow"
        "Sumatran tiger in the forest" = "prowled underbrush"
        "south China tiger in the hills" = "lurked mysteriously"
        "Indochinese tiger in the grove" = "prowled silently"
        "Malayan tiger in the jungle" = "stalked stealthily"
        "Tasmanian devil in the bush" = "scavenged fiercely"
        "thylacine in the memory" = "prowled mythically"
        "quoll in the scrub" = "hunted at night"
        "dibbler in the undergrowth" = "searched for food"
        "bandicoot in the bush" = "scurried busily"
        "bilby under the stars" = "dug swiftly"
        "tree kangaroo in the canopy" = "leaped between branches"
        "rock wallaby in the hills" = "hopped agilely"
        "padymelon in the underbrush" = "hopped quietly"
        "bettong in the forest" = "foraged at night"
        "potoroo in the scrub" = "hopped cautiously"
        "callaloo in the outback" = "bounded strongly"
        "antechinus in the tree" = "climbed nimbly"
        "dunnart in the sand" = "scurried quickly"
        "phascogale in the bush" = "climbed rapidly"
        "kowari in the desert" = "foraged at night"
        "mulgara in the scrub" = "hunted fiercely"
        "bandicoot in the grass" = "scurried rapidly"
        "quoll in the night" = "hunted stealthily"
        "thylacine in the forest" = "stalked silently"
        "Tasmanian devil in the night" = "scavenged aggressively"
        "dibbler in the scrub" = "searched for prey"
        "rock wallaby in the mountains" = "leaped adeptly"
        "padymelon in the bush" = "hopped softly"
        "potoroo in the underbrush" = "foraged quietly"
        "bison in the prairie" = "roamed widely"
        "condor in the sky" = "soared majestically"
        "dingo in the outback" = "howled under the moon"
        "echidna in the scrub" = "foraged for ants"
        "frigatebird over the sea" = "glided on the breeze"
        "gala in the eucalyptus" = "chatted noisily"
        "hyrax on the rocks" = "basked in the sun"
        "ibis by the river" = "probed the mud"
        "jackal in the savanna" = "scavenged cleverly"
        "kudu in the bush" = "leaped gracefully"
        "lorikeet in the blossom" = "fed on nectar"
    }

    $Subjects = $SubjectActions.Keys

    $Sentences=@()
    
    for ($i = $Start-1; $i -lt $End; $i++){
        $Phrase = "This is the $($(
            for ($j = $i; $j -ge 0; $j--){
                $Modyfier = $SubjectActions[$Subjects[$j]]
                "$($Subjects[$j]) that $($Modyfier)"
            }) -join " the ")."
        $Sentences += $Phrase 
    }

    return $Sentences -join "`n"
}